version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "Update "
      prefix-development: "Update "
      include: "scope"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "Update "
      prefix-development: "Update "
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "Update "
      prefix-development: "Update "
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/deployments"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "Update "
      prefix-development: "Update "
      include: "scope"
