// Code generated by templ@v0.2.316 DO NOT EDIT.

package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func LoginPage(csrfToken string, validationErrs map[string]string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<div class=\"flex items-center min-h-screen bg-white\"><div class=\"container mx-auto\"><div class=\"max-w-xl mx-auto my-10\">")
		if err != nil {
			return err
		}
		err = logo("mt-6 text-8xl", "h-20").Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("<div class=\"m-7 p-8 border border-gray-200 rounded-md\"><form action=\"/login\" method=\"post\"><input type=\"hidden\" name=\"stuff.csrf.token\" value=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(csrfToken))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\">")
		if err != nil {
			return err
		}
		err = Input(InputProps{
			Class:         "mb-6",
			Type:          "text",
			Name:          "username",
			Placeholder:   "Username",
			Label:         "Username",
			Required:      true,
			Icon:          Icon("user", "w-[24px] h-[24px]"),
			ValidationErr: validationErrs["username"],
		}).Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		err = Input(InputProps{
			Class:         "mb-6",
			Type:          "password",
			Name:          "password",
			Placeholder:   "Password",
			Label:         "Password",
			Icon:          Icon("password", "w-[24px] h-[24px]"),
			Required:      true,
			AutoComplete:  "current-password",
			ValidationErr: validationErrs["password"],
		}).Render(ctx, templBuffer)
		if err != nil {
			return err
		}
		var_2 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
			templBuffer, templIsBuffer := w.(*bytes.Buffer)
			if !templIsBuffer {
				templBuffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templBuffer)
			}
			var_3 := `Login`
			_, err = templBuffer.WriteString(var_3)
			if err != nil {
				return err
			}
			if !templIsBuffer {
				_, err = io.Copy(w, templBuffer)
			}
			return err
		})
		err = Button(ButtonProps{Type: "submit", Class: "w-full py-4"}).Render(templ.WithChildren(ctx, var_2), templBuffer)
		if err != nil {
			return err
		}
		if validationErrs["general"] != "" {
			_, err = templBuffer.WriteString("<span class=\"text-red-500\">")
			if err != nil {
				return err
			}
			var var_4 string = validationErrs["general"]
			_, err = templBuffer.WriteString(templ.EscapeString(var_4))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</span>")
			if err != nil {
				return err
			}
		}
		_, err = templBuffer.WriteString("</form></div></div></div></div>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = io.Copy(w, templBuffer)
		}
		return err
	})
}
