// Code generated by BobGen sqlite v0.22.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"github.com/aarondl/opt/null"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
)

// AssetsFT is an object representing the database table.
type AssetsFT struct {
	ID        null.Val[string] `db:"id" `
	Data      null.Val[string] `db:"data" `
	AssetsFTS null.Val[string] `db:"assets_fts" `
	Rank      null.Val[string] `db:"rank" `
}

// AssetsFTSlice is an alias for a slice of pointers to AssetsFT.
// This should almost always be used instead of []*AssetsFT.
type AssetsFTSlice []*AssetsFT

// AssetsFTS contains methods to work with the assets_fts view
var AssetsFTS = sqlite.NewViewx[*AssetsFT, AssetsFTSlice]("", "assets_fts")

// AssetsFTSQuery is a query on the assets_fts view
type AssetsFTSQuery = *sqlite.ViewQuery[*AssetsFT, AssetsFTSlice]

// AssetsFTSStmt is a prepared statment on assets_fts
type AssetsFTSStmt = bob.QueryStmt[*AssetsFT, AssetsFTSlice]

type assetsFTColumnNames struct {
	ID        string
	Data      string
	AssetsFTS string
	Rank      string
}

var AssetsFTColumns = struct {
	ID        sqlite.Expression
	Data      sqlite.Expression
	AssetsFTS sqlite.Expression
	Rank      sqlite.Expression
}{
	ID:        sqlite.Quote("assets_fts", "id"),
	Data:      sqlite.Quote("assets_fts", "data"),
	AssetsFTS: sqlite.Quote("assets_fts", "assets_fts"),
	Rank:      sqlite.Quote("assets_fts", "rank"),
}

type assetsFTWhere[Q sqlite.Filterable] struct {
	ID        sqlite.WhereNullMod[Q, string]
	Data      sqlite.WhereNullMod[Q, string]
	AssetsFTS sqlite.WhereNullMod[Q, string]
	Rank      sqlite.WhereNullMod[Q, string]
}

func AssetsFTWhere[Q sqlite.Filterable]() assetsFTWhere[Q] {
	return assetsFTWhere[Q]{
		ID:        sqlite.WhereNull[Q, string](AssetsFTColumns.ID),
		Data:      sqlite.WhereNull[Q, string](AssetsFTColumns.Data),
		AssetsFTS: sqlite.WhereNull[Q, string](AssetsFTColumns.AssetsFTS),
		Rank:      sqlite.WhereNull[Q, string](AssetsFTColumns.Rank),
	}
}
