// Code generated by BobGen sqlite v0.22.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"github.com/aarondl/opt/null"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
)

// CustomAttrName is an object representing the database table.
type CustomAttrName struct {
	Name null.Val[string] `db:"name" `
	Type null.Val[string] `db:"type" `
}

// CustomAttrNameSlice is an alias for a slice of pointers to CustomAttrName.
// This should almost always be used instead of []*CustomAttrName.
type CustomAttrNameSlice []*CustomAttrName

// CustomAttrNames contains methods to work with the custom_attr_names view
var CustomAttrNames = sqlite.NewViewx[*CustomAttrName, CustomAttrNameSlice]("", "custom_attr_names")

// CustomAttrNamesQuery is a query on the custom_attr_names view
type CustomAttrNamesQuery = *sqlite.ViewQuery[*CustomAttrName, CustomAttrNameSlice]

// CustomAttrNamesStmt is a prepared statment on custom_attr_names
type CustomAttrNamesStmt = bob.QueryStmt[*CustomAttrName, CustomAttrNameSlice]

type customAttrNameColumnNames struct {
	Name string
	Type string
}

var CustomAttrNameColumns = struct {
	Name sqlite.Expression
	Type sqlite.Expression
}{
	Name: sqlite.Quote("custom_attr_names", "name"),
	Type: sqlite.Quote("custom_attr_names", "type"),
}

type customAttrNameWhere[Q sqlite.Filterable] struct {
	Name sqlite.WhereNullMod[Q, string]
	Type sqlite.WhereNullMod[Q, string]
}

func CustomAttrNameWhere[Q sqlite.Filterable]() customAttrNameWhere[Q] {
	return customAttrNameWhere[Q]{
		Name: sqlite.WhereNull[Q, string](CustomAttrNameColumns.Name),
		Type: sqlite.WhereNull[Q, string](CustomAttrNameColumns.Type),
	}
}
