// Code generated by BobGen sqlite v0.22.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"github.com/aarondl/opt/null"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
)

// Manufacturer is an object representing the database table.
type Manufacturer struct {
	Name null.Val[string] `db:"name" `
}

// ManufacturerSlice is an alias for a slice of pointers to Manufacturer.
// This should almost always be used instead of []*Manufacturer.
type ManufacturerSlice []*Manufacturer

// Manufacturers contains methods to work with the manufacturers view
var Manufacturers = sqlite.NewViewx[*Manufacturer, ManufacturerSlice]("", "manufacturers")

// ManufacturersQuery is a query on the manufacturers view
type ManufacturersQuery = *sqlite.ViewQuery[*Manufacturer, ManufacturerSlice]

// ManufacturersStmt is a prepared statment on manufacturers
type ManufacturersStmt = bob.QueryStmt[*Manufacturer, ManufacturerSlice]

type manufacturerColumnNames struct {
	Name string
}

var ManufacturerColumns = struct {
	Name sqlite.Expression
}{
	Name: sqlite.Quote("manufacturers", "name"),
}

type manufacturerWhere[Q sqlite.Filterable] struct {
	Name sqlite.WhereNullMod[Q, string]
}

func ManufacturerWhere[Q sqlite.Filterable]() manufacturerWhere[Q] {
	return manufacturerWhere[Q]{
		Name: sqlite.WhereNull[Q, string](ManufacturerColumns.Name),
	}
}
