// Code generated by BobGen sqlite v0.22.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"github.com/aarondl/opt/null"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/sqlite"
)

// PositionCode is an object representing the database table.
type PositionCode struct {
	Code null.Val[string] `db:"code" `
}

// PositionCodeSlice is an alias for a slice of pointers to PositionCode.
// This should almost always be used instead of []*PositionCode.
type PositionCodeSlice []*PositionCode

// PositionCodes contains methods to work with the position_codes view
var PositionCodes = sqlite.NewViewx[*PositionCode, PositionCodeSlice]("", "position_codes")

// PositionCodesQuery is a query on the position_codes view
type PositionCodesQuery = *sqlite.ViewQuery[*PositionCode, PositionCodeSlice]

// PositionCodesStmt is a prepared statment on position_codes
type PositionCodesStmt = bob.QueryStmt[*PositionCode, PositionCodeSlice]

type positionCodeColumnNames struct {
	Code string
}

var PositionCodeColumns = struct {
	Code sqlite.Expression
}{
	Code: sqlite.Quote("position_codes", "code"),
}

type positionCodeWhere[Q sqlite.Filterable] struct {
	Code sqlite.WhereNullMod[Q, string]
}

func PositionCodeWhere[Q sqlite.Filterable]() positionCodeWhere[Q] {
	return positionCodeWhere[Q]{
		Code: sqlite.WhereNull[Q, string](PositionCodeColumns.Code),
	}
}
