// Code generated by BobGen sqlite v0.22.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"github.com/aarondl/opt/null"
	"github.com/jaswdr/faker"
	models "github.com/kodeshack/stuff/storage/database/sqlite/models"
)

type LocationMod interface {
	Apply(*LocationTemplate)
}

type LocationModFunc func(*LocationTemplate)

func (f LocationModFunc) Apply(n *LocationTemplate) {
	f(n)
}

type LocationModSlice []LocationMod

func (mods LocationModSlice) Apply(n *LocationTemplate) {
	for _, f := range mods {
		f.Apply(n)
	}
}

// LocationTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type LocationTemplate struct {
	Name func() null.Val[string]

	f *Factory
}

// Apply mods to the LocationTemplate
func (o *LocationTemplate) Apply(mods ...LocationMod) {
	for _, mod := range mods {
		mod.Apply(o)
	}
}

// toModel returns an *models.Location
// this does nothing with the relationship templates
func (o LocationTemplate) toModel() *models.Location {
	m := &models.Location{}

	if o.Name != nil {
		m.Name = o.Name()
	}

	return m
}

// toModels returns an models.LocationSlice
// this does nothing with the relationship templates
func (o LocationTemplate) toModels(number int) models.LocationSlice {
	m := make(models.LocationSlice, number)

	for i := range m {
		m[i] = o.toModel()
	}

	return m
}

// setModelRels creates and sets the relationships on *models.Location
// according to the relationships in the template. Nothing is inserted into the db
func (t LocationTemplate) setModelRels(o *models.Location) {}

// Build returns an *models.Location
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use LocationTemplate.Create
func (o LocationTemplate) Build() *models.Location {
	m := o.toModel()
	o.setModelRels(m)

	return m
}

// BuildMany returns an models.LocationSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use LocationTemplate.CreateMany
func (o LocationTemplate) BuildMany(number int) models.LocationSlice {
	m := make(models.LocationSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

// Location has methods that act as mods for the LocationTemplate
var LocationMods locationMods

type locationMods struct{}

func (m locationMods) RandomizeAllColumns(f *faker.Faker) LocationMod {
	return LocationModSlice{
		LocationMods.RandomName(f),
	}
}

// Set the model columns to this value
func (m locationMods) Name(val null.Val[string]) LocationMod {
	return LocationModFunc(func(o *LocationTemplate) {
		o.Name = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m locationMods) NameFunc(f func() null.Val[string]) LocationMod {
	return LocationModFunc(func(o *LocationTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m locationMods) UnsetName() LocationMod {
	return LocationModFunc(func(o *LocationTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m locationMods) RandomName(f *faker.Faker) LocationMod {
	return LocationModFunc(func(o *LocationTemplate) {
		o.Name = func() null.Val[string] {
			return randomNull[string](f)
		}
	})
}

func (m locationMods) ensureName(f *faker.Faker) LocationMod {
	return LocationModFunc(func(o *LocationTemplate) {
		if o.Name != nil {
			return
		}

		o.Name = func() null.Val[string] {
			return randomNull[string](f)
		}
	})
}
