// Code generated by BobGen sqlite v0.22.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"github.com/aarondl/opt/null"
	"github.com/jaswdr/faker"
	models "github.com/kodeshack/stuff/storage/database/sqlite/models"
)

type ManufacturerMod interface {
	Apply(*ManufacturerTemplate)
}

type ManufacturerModFunc func(*ManufacturerTemplate)

func (f ManufacturerModFunc) Apply(n *ManufacturerTemplate) {
	f(n)
}

type ManufacturerModSlice []ManufacturerMod

func (mods ManufacturerModSlice) Apply(n *ManufacturerTemplate) {
	for _, f := range mods {
		f.Apply(n)
	}
}

// ManufacturerTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type ManufacturerTemplate struct {
	Name func() null.Val[string]

	f *Factory
}

// Apply mods to the ManufacturerTemplate
func (o *ManufacturerTemplate) Apply(mods ...ManufacturerMod) {
	for _, mod := range mods {
		mod.Apply(o)
	}
}

// toModel returns an *models.Manufacturer
// this does nothing with the relationship templates
func (o ManufacturerTemplate) toModel() *models.Manufacturer {
	m := &models.Manufacturer{}

	if o.Name != nil {
		m.Name = o.Name()
	}

	return m
}

// toModels returns an models.ManufacturerSlice
// this does nothing with the relationship templates
func (o ManufacturerTemplate) toModels(number int) models.ManufacturerSlice {
	m := make(models.ManufacturerSlice, number)

	for i := range m {
		m[i] = o.toModel()
	}

	return m
}

// setModelRels creates and sets the relationships on *models.Manufacturer
// according to the relationships in the template. Nothing is inserted into the db
func (t ManufacturerTemplate) setModelRels(o *models.Manufacturer) {}

// Build returns an *models.Manufacturer
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ManufacturerTemplate.Create
func (o ManufacturerTemplate) Build() *models.Manufacturer {
	m := o.toModel()
	o.setModelRels(m)

	return m
}

// BuildMany returns an models.ManufacturerSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ManufacturerTemplate.CreateMany
func (o ManufacturerTemplate) BuildMany(number int) models.ManufacturerSlice {
	m := make(models.ManufacturerSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

// Manufacturer has methods that act as mods for the ManufacturerTemplate
var ManufacturerMods manufacturerMods

type manufacturerMods struct{}

func (m manufacturerMods) RandomizeAllColumns(f *faker.Faker) ManufacturerMod {
	return ManufacturerModSlice{
		ManufacturerMods.RandomName(f),
	}
}

// Set the model columns to this value
func (m manufacturerMods) Name(val null.Val[string]) ManufacturerMod {
	return ManufacturerModFunc(func(o *ManufacturerTemplate) {
		o.Name = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m manufacturerMods) NameFunc(f func() null.Val[string]) ManufacturerMod {
	return ManufacturerModFunc(func(o *ManufacturerTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m manufacturerMods) UnsetName() ManufacturerMod {
	return ManufacturerModFunc(func(o *ManufacturerTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m manufacturerMods) RandomName(f *faker.Faker) ManufacturerMod {
	return ManufacturerModFunc(func(o *ManufacturerTemplate) {
		o.Name = func() null.Val[string] {
			return randomNull[string](f)
		}
	})
}

func (m manufacturerMods) ensureName(f *faker.Faker) ManufacturerMod {
	return ManufacturerModFunc(func(o *ManufacturerTemplate) {
		if o.Name != nil {
			return
		}

		o.Name = func() null.Val[string] {
			return randomNull[string](f)
		}
	})
}
