name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  LintAndTest:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.21.1
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.1
    - uses: actions/setup-node@v3
      with:
    - name: Install just 1.14.0
        node-version: '21'
      uses: kodeshack/action-install-gh-release@v1.4.2
      with:
        owner: casey
        repo: just
        version: '1.13.0'
        test: just --version
    - name: Check out code
      uses: actions/checkout@v4
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install staticcheck@2023.1.5
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@2023.1.5
    - name: golangci-lint@v1.55.1
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.1
    - name: "Lint"
      run: |
        just lint
    - name: "Test"
      run: |
        just test
