name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  LintAndTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: 1.21.4
    - uses: actions/setup-node@v3
      with:
        node-version: '21'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: Install just 1.16.0
      uses: kodeshack/action-install-gh-release@v1.4.2
      with:
        owner: casey
        repo: just
        version: '1.16.0'
        test: just --version
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Install staticcheck
      run: |
        go install -mod=readonly honnef.co/go/tools/cmd/staticcheck
    - name: Install golangci-lint
      run: |
        go install -mod=readonly github.com/golangci/golangci-lint/cmd/golangci-lint
    - name: "Lint"
      run: |
        just lint
    - name: "Test"
      run: |
        just test
