name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  LintAndTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: 1.21.4
    - uses: actions/setup-node@v4
      with:
        node-version: '21'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: Install just 1.16.0
      uses: kodeshack/action-install-gh-release@v1.4.2
      with:
        owner: casey
        repo: just
        version: '1.16.0'
        test: just --version
    - name: Install gotestsum
      run: |
        go install -mod=readonly gotest.tools/gotestsum
    - name: Install staticcheck and golangci-lint
      run: |
        go install -mod=readonly honnef.co/go/tools/cmd/staticcheck
        go install -mod=readonly github.com/golangci/golangci-lint/cmd/golangci-lint

    - name: "Lint"
      run: |
        just lint-ci

    - name: "Test"
      run: |
        just test-ci

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        check_name: "Test Results"
        files: |
          test.junit.xml

    - name: Publish Lint Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        check_name: "Lint Results"
        files: |
          lint.junit.xml

  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: 1.21.4
    - uses: actions/setup-node@v4
      with:
        node-version: '21'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: Install just 1.16.0
      uses: kodeshack/action-install-gh-release@v1.4.2
      with:
        owner: casey
        repo: just
        version: '1.16.0'
        test: just --version

    - name: "Build"
      run: |
        just build
